# Generated by Django 4.2.1 on 2023-06-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='niveau2',
            field=models.IntegerField(default=17, null=True),
        ),
    ]
