# Generated by Django 4.2.1 on 2023-06-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_etudiant_niveau2'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjugaison',
            name='texte',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lemme',
            name='ant_texte',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lemme',
            name='syn_texte',
            field=models.TextField(null=True),
        ),
    ]
