# Generated by Django 4.2.1 on 2023-06-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conjugaison_texte_lemme_ant_texte_lemme_syn_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_elle',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_elles_P',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_il',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_ils_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_ils_P',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_je',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_nous',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_tu_F',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_tu_M',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_vous_2M',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_vous_PF',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='conjugaison',
            name='prnm_vous_PM',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
