# Generated by Django 4.2.1 on 2023-07-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_conjugaison_prnm_elle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exo4',
            name='table_conjugaison',
            field=models.TextField(null=True),
        ),
    ]
