# Generated by Django 4.2.1 on 2023-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_exo4_table_conjugaison_exo4_temps_conjugaison'),
    ]

    operations = [
        migrations.AddField(
            model_name='lemme',
            name='rank',
            field=models.BigIntegerField(null=True),
        ),
    ]
