# Generated by Django 4.2.1 on 2023-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lemme_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='definition',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='example',
            field=models.TextField(null=True),
        ),
    ]
