# Generated by Django 4.2.1 on 2023-07-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_definition_definition_alter_example_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='exo4',
            name='cnjg',
            field=models.TextField(null=True),
        ),
    ]
